-- Create the materials table
CREATE TABLE public.materials (
    id bigint generated by default as identity primary key,
    title text not null,
    file_url text not null,
    file_size bigint not null,
    course_id bigint references public.courses on delete cascade,
    lesson_id bigint references public.lessons on delete cascade,
    session_id bigint references public.sessions on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.materials;

-- Allow public read access for materials (anyone can view materials metadata)
CREATE POLICY "Enable read access for all users" ON public.materials FOR SELECT USING (true);

-- Allow authenticated users (admin) to manage materials
CREATE POLICY "Enable all access for authenticated users" ON public.materials FOR ALL USING (auth.role() = 'authenticated');
