-- Drop the old lessons table entirely so we can recreate it with the new schema.
-- (The user said they will delete existing records and we can ignore current data)
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.lessons CASCADE;

-- Create the new lessons table (now just a grouping for sessions)
CREATE TABLE public.lessons (
    id bigint generated by default as identity primary key,
    course_id bigint references public.courses on delete cascade,
    title text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create the new sessions table
CREATE TABLE public.sessions (
    id bigint generated by default as identity primary key,
    lesson_id bigint references public.lessons on delete cascade,
    title text not null,
    youtube_link text not null,
    is_free boolean default false not null,
    price integer default 0 not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Allow public read access (or authenticated users depending on your overall policy)
-- Note: Assuming similar policies as before where users can view metadata,
-- but you enforce payment for the video in the frontend or via other policies.
CREATE POLICY "Enable read access for all users" ON public.lessons FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.sessions FOR SELECT USING (true);

-- Allow admin write access (You may need to adjust these policies based on your admin auth setup, e.g. checking an admin_users table)
CREATE POLICY "Enable all access for authenticated users" ON public.lessons FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON public.sessions FOR ALL USING (auth.role() = 'authenticated');
