-- Create student profiles table linked to Supabase auth
CREATE TABLE public.student_profiles (
    id uuid references auth.users on delete cascade primary key,
    student_id text unique,
    full_name text not null,
    is_approved boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
ALTER TABLE public.student_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.student_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can view and edit all profiles" ON public.student_profiles FOR ALL USING (auth.role() = 'authenticated'); -- Note: in production, check actual admin role/table

-- Add visibility to courses
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS visibility text default 'assignable' check (visibility in ('assignable', 'public'));

-- Create enrollments table
CREATE TABLE public.enrollments (
    id bigint generated by default as identity primary key,
    user_id uuid references public.student_profiles(id) on delete cascade not null,
    course_id bigint references public.courses(id) on delete cascade not null,
    status text default 'active' check (status in ('active', 'inactive')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, course_id)
);

-- Enable RLS for enrollments
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own enrollments" ON public.enrollments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view and edit all enrollments" ON public.enrollments FOR ALL USING (auth.role() = 'authenticated');

-- Function and Trigger to create profile automatically and generate Student ID
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
    new_student_id text;
    year_prefix text;
    seq_val bigint;
BEGIN
    year_prefix := to_char(now(), 'YYYY');

    -- In a real scenario, you'd use a sequence. For simplicity, we just count.
    SELECT count(*) + 1 INTO seq_val FROM public.student_profiles WHERE student_id LIKE year_prefix || '-%';

    new_student_id := year_prefix || '-' || lpad(seq_val::text, 4, '0');

    INSERT INTO public.student_profiles (id, full_name, student_id, is_approved)
    VALUES (new.id, new.raw_user_meta_data->>'full_name', new_student_id, false);

    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if it exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Recreate trigger
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
